# Generated by Django 6.0.3 on 2026-06-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_ledgerentrymodel_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentrymodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ledgerentrymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ledgerentrymodel',
            name='entry_type',
            field=models.CharField(max_length=20),
        ),
    ]
