# Generated by Django 6.0.3 on 2026-03-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
