# Generated by Django 6.0.3 on 2026-06-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountmodel_is_frozen_accountmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
