# Generated by Django 6.0.3 on 2026-06-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='is_frozen',
            new_name='frozen',
        ),
    ]
