# Generated by Django 6.0.3 on 2026-06-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_frozen_accountmodel_frozen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='frozen',
            new_name='is_frozen',
        ),
    ]
